[build]
  publish = "site"
  command = "node ./scripts/netlify-generate-env.cjs"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/admin"
  to = "/admin/admin-login.html"
  status = 302

[[redirects]]
  from = "/admin/"
  to = "/admin/admin-login.html"
  status = 302

[[redirects]]
  from = "http://kalungacomunicacoes.org/*"
  to = "https://kalungacomunicacoes.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.kalungacomunicacoes.org/*"
  to = "https://kalungacomunicacoes.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.kalungacomunicacoes.org/*"
  to = "https://kalungacomunicacoes.org/:splat"
  status = 301
  force = true
